/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alumno
 */

import java.applet.AudioClip;
import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.util.logging.Level;
import java.util.logging.Logger;


public class frm_calculadora extends javax.swing.JFrame {

    /**
     * Creates new form frm_calculadora
     */
    public frm_calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frm_manual = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        frm_lectura = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_lectura = new javax.swing.JTextArea();
        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_multip = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        txt_pantalla = new javax.swing.JTextField();
        lbl_adv = new javax.swing.JLabel();
        lbl_op = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_nuevo = new javax.swing.JMenuItem();
        mn_historial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Mn_manual = new javax.swing.JMenuItem();

        frm_manual.setAlwaysOnTop(true);
        frm_manual.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel15.setText("Al utilizar la opcion \"Nuevo\" en el menu de \"Opciones\", se guardara la operacion");

        jLabel16.setText("realizada y al utilizar la opcion de \" Historial \" usted podra ver cuales son las");

        jLabel17.setText("Usted podra utilizar los botones de la pantalla o las teclas en su teclado. Al");

        jLabel18.setText("ingresar un valor, este sera guardado al momento en el que presione la teclas");

        jLabel19.setText("operaciones realizadas anteriormente.");

        jLabel20.setText("o botones de suma, resta, multiplicacion o dovision, seguido aparecera arriba ");

        jLabel21.setText("el primer valor y el tipo de operacion que se esta realizando. Cuando ingrese ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Bienvenido, esta es una calculadora de opereciones aritmeticas");

        jLabel23.setText("el segundo valor debera utilizar el boton o tecla del igual, de esta manera se ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Manual de usuario");

        jLabel25.setText("le dara el resultado en la pantalla.");

        jLabel26.setText("Esta calculadora es capas re realizar sumas, restas, multiplicaciones y divisiones.");
        jLabel26.setToolTipText("");

        jLabel27.setText("  ----------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout frm_manualLayout = new javax.swing.GroupLayout(frm_manual.getContentPane());
        frm_manual.getContentPane().setLayout(frm_manualLayout);
        frm_manualLayout.setHorizontalGroup(
            frm_manualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_manualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frm_manualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frm_manualLayout.createSequentialGroup()
                        .addGroup(frm_manualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(frm_manualLayout.createSequentialGroup()
                .addGroup(frm_manualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frm_manualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        frm_manualLayout.setVerticalGroup(
            frm_manualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_manualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(30, 30, 30)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        frm_lectura.setMinimumSize(new java.awt.Dimension(500, 500));

        txa_lectura.setColumns(20);
        txa_lectura.setRows(5);
        jScrollPane1.setViewportView(txa_lectura);

        javax.swing.GroupLayout frm_lecturaLayout = new javax.swing.GroupLayout(frm_lectura.getContentPane());
        frm_lectura.getContentPane().setLayout(frm_lecturaLayout);
        frm_lecturaLayout.setHorizontalGroup(
            frm_lecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frm_lecturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        frm_lecturaLayout.setVerticalGroup(
            frm_lecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frm_lecturaLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_multip.setText("*");
        btn_multip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multipActionPerformed(evt);
            }
        });

        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        btn_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_1KeyPressed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        txt_pantalla.setEditable(false);
        txt_pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pantallaActionPerformed(evt);
            }
        });
        txt_pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pantallaKeyPressed(evt);
            }
        });

        lbl_op.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu1.setText("Opciones");

        mn_nuevo.setText("Nuevo");
        mn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(mn_nuevo);

        mn_historial.setText("Historial");
        mn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_historialActionPerformed(evt);
            }
        });
        jMenu1.add(mn_historial);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        Mn_manual.setText("Manual de Usuario");
        Mn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_manualActionPerformed(evt);
            }
        });
        jMenu2.add(Mn_manual);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_op, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_adv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_multip, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lbl_op, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_adv, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multip, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double x1=0,x2=0,x3=0;
    String operacion;
    //
    
    
    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"1");
        
        //AudioCLip sound;
        //sound = java.applet.Applet.newAudioClip(url)
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void txt_pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pantallaActionPerformed

    private void btn_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1KeyPressed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        this.txt_pantalla.setText(this.txt_pantalla.getText()+"0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        this.x1=Double.parseDouble(this.txt_pantalla.getText());
        this.lbl_op.setText(Double.toString(this.x1)+"  +");
        this.operacion="+";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        this.x2=Double.parseDouble(this.txt_pantalla.getText());
        
        switch(this.operacion){
            case "+":{
                this.x3=this.x1+this.x2;
                this.txt_pantalla.setText(Double.toString(this.x3));
                this.lbl_op.setText("");
            }break;
            case "-":{
                this.x3=this.x1-this.x2;
                this.txt_pantalla.setText(Double.toString(this.x3));
                this.lbl_op.setText("");
            }break;
            case "*":{
                this.x3=this.x1*this.x2;
                this.txt_pantalla.setText(Double.toString(this.x3));
                this.lbl_op.setText("");
            }break;
            case "/":{
                if(this.x2==0){
                    this.lbl_adv.setText("Ningun numero puede ser dividido en 0, intentelo de nuevo");
                    this.txt_pantalla.setText("");
                }else{
                    this.x3=this.x1/this.x2;
                    this.txt_pantalla.setText(Double.toString(this.x3));
                    this.lbl_op.setText("");
                }
                
            }break;
        }
        
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        this.x1=Double.parseDouble(this.txt_pantalla.getText());
        this.lbl_op.setText(Double.toString(this.x1)+"  -");
        this.operacion="-";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_multipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multipActionPerformed
        // TODO add your handling code here:
        this.x1=Double.parseDouble(this.txt_pantalla.getText());
        this.lbl_op.setText(Double.toString(this.x1)+"  *");
        this.operacion="*";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_multipActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        this.x1=Double.parseDouble(this.txt_pantalla.getText());
        this.lbl_op.setText(Double.toString(this.x1)+"  /");
        this.operacion="/";
        this.txt_pantalla.setText("");
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
        if(!(this.txt_pantalla.getText().contains("."))){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+".");
        }
        
    }//GEN-LAST:event_btn_puntoActionPerformed

    
    
    private void txt_pantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pantallaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD1 || evt.getKeyCode()==KeyEvent.VK_1){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"1");    
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD2 || evt.getKeyCode()==KeyEvent.VK_2){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"2");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD3 || evt.getKeyCode()==KeyEvent.VK_3){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"3");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD4 || evt.getKeyCode()==KeyEvent.VK_4){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"4");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD5 || evt.getKeyCode()==KeyEvent.VK_5){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"5");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD6 || evt.getKeyCode()==KeyEvent.VK_6){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"6");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD7 || evt.getKeyCode()==KeyEvent.VK_7){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"7");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD8 || evt.getKeyCode()==KeyEvent.VK_8){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"8");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD9 || evt.getKeyCode()==KeyEvent.VK_9){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"9");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_NUMPAD0 || evt.getKeyCode()==KeyEvent.VK_0){
            this.txt_pantalla.setText(this.txt_pantalla.getText()+"0");
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_PERIOD){
            if(!(this.txt_pantalla.getText().contains("."))){
                this.txt_pantalla.setText(this.txt_pantalla.getText()+".");
            }
        }
        if(evt.getKeyCode()==KeyEvent.VK_ADD ||evt.getKeyCode()==KeyEvent.VK_PLUS){
            this.x1=Double.parseDouble(this.txt_pantalla.getText());
            this.lbl_op.setText(Double.toString(this.x1)+"  +");
            this.operacion="+";
            this.txt_pantalla.setText("");
        }
        if(evt.getKeyCode()==KeyEvent.VK_SUBTRACT ||evt.getKeyCode()==KeyEvent.VK_MINUS){
            this.x1=Double.parseDouble(this.txt_pantalla.getText());
            this.lbl_op.setText(Double.toString(this.x1)+"  -");
            this.operacion="-";
            this.txt_pantalla.setText("");
        }
        if(evt.getKeyCode()==KeyEvent.VK_MULTIPLY){
            this.x1=Double.parseDouble(this.txt_pantalla.getText());
            this.lbl_op.setText(Double.toString(this.x1)+"  *");
            this.operacion="*";
            this.txt_pantalla.setText("");
        }
        if(evt.getKeyCode()==KeyEvent.VK_DIVIDE||evt.getKeyCode()==KeyEvent.VK_SLASH){
            this.x1=Double.parseDouble(this.txt_pantalla.getText());
            this.lbl_op.setText(Double.toString(this.x1)+"  /");
            this.operacion="/";
            this.txt_pantalla.setText("");
        }
        if(evt.getKeyCode()==KeyEvent.VK_EQUALS||evt.getKeyCode()==KeyEvent.VK_ENTER){
             this.x2=Double.parseDouble(this.txt_pantalla.getText());
        
            switch(this.operacion){
                case "+":{
                    this.x3=this.x1+this.x2;
                    this.txt_pantalla.setText(Double.toString(this.x3));
                    this.lbl_op.setText("");
                }break;
                case "-":{
                    this.x3=this.x1-this.x2;
                    this.txt_pantalla.setText(Double.toString(this.x3));
                    this.lbl_op.setText("");
                }break;
                case "*":{
                    this.x3=this.x1*this.x2;
                    this.txt_pantalla.setText(Double.toString(this.x3));
                    this.lbl_op.setText("");
                }break;
                case "/":{
                    if(this.x2==0){
                        this.lbl_adv.setText("Ningun numero puede ser dividido en 0, intentelo de nuevo");
                        this.txt_pantalla.setText("");
                    }else{
                        this.x3=this.x1/this.x2;
                        this.txt_pantalla.setText(Double.toString(this.x3));
                        this.lbl_op.setText("");
                    }

                }break;
            }
        }
        if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
            this.txt_pantalla.setText("");
        }
        
    }//GEN-LAST:event_txt_pantallaKeyPressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
       // jDialog1.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void Mn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_manualActionPerformed
        // TODO add your handling code here:
        this.frm_manual.setVisible(true);
    }//GEN-LAST:event_Mn_manualActionPerformed

    private void mn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_historialActionPerformed
       switch(this.operacion){
        case "+":{
            this.frm_lectura.setVisible(true);
        this.txa_lectura.setText(Double.toString(this.x1)+" + "+Double.toString(this.x2)+" = "+Double.toString(this.x3));
    }break;
    case "-":{
        this.frm_lectura.setVisible(true);
        this.txa_lectura.setText(Double.toString(this.x1)+" - "+Double.toString(this.x2)+" = "+Double.toString(this.x3));
    }break;
    case "*":{
        this.frm_lectura.setVisible(true);
        this.txa_lectura.setText(Double.toString(this.x1)+" * "+Double.toString(this.x2)+" = "+Double.toString(this.x3));
    }break;
    case "/":{
        this.frm_lectura.setVisible(true);
        this.txa_lectura.setText(Double.toString(this.x1)+" / "+Double.toString(this.x2)+" = "+Double.toString(this.x3));
    }break;
    } 
        
        this.txa_lectura.setText(Double.toString(this.x1)+" + "+Double.toString(this.x2)+" = "+Double.toString(this.x3));
    }//GEN-LAST:event_mn_historialActionPerformed

    private void mn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_nuevoActionPerformed
        // TODO add your handling code here:
        switch(this.operacion){
            case "+":{
                String valores = Double.toString(this.x1) + " + " + Double.toString(this.x2)+" = " + Double.toString(this.x3);
                File archivo = new File("bitacora.txt");
                
            try {
                BufferedWriter archivo2=new BufferedWriter(new FileWriter(archivo));
                archivo2.newLine();
                archivo2.append(valores);
                archivo2.newLine();
                
                archivo2.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
            /*try {
                FileWriter escribir = new FileWriter(archivo);
                escribir.write(valores);
                
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }  */ 
            this.txt_pantalla.setText("");
            }break;
            case "-":{
                String valores = Double.toString(this.x1) + " - " + Double.toString(this.x2)+" = " + Double.toString(this.x3);
                File archivo = new File("bitacora.txt");
            try {
                BufferedWriter archivo2=new BufferedWriter(new FileWriter(archivo));
                archivo2.newLine();
                archivo2.append(valores);
                archivo2.newLine();
                
                archivo2.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.txt_pantalla.setText("");
            }break;
            case "*":{
                String valores = Double.toString(this.x1) + " * " + Double.toString(this.x2)+" = " + Double.toString(this.x3);
                File archivo = new File("bitacora.txt");
            try {
                BufferedWriter archivo2=new BufferedWriter(new FileWriter(archivo));
                archivo2.newLine();
                archivo2.append(valores);
                archivo2.newLine();
                
                archivo2.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.txt_pantalla.setText("");
            }break;
            case "/":{
                String valores = Double.toString(this.x1) + " / " + Double.toString(this.x2)+" = " + Double.toString(this.x3);
                File archivo = new File("bitacora.txt");
            try {
                BufferedWriter archivo2=new BufferedWriter(new FileWriter(archivo));
                archivo2.newLine();
                archivo2.append(valores);
                archivo2.newLine();
                
                archivo2.close();
            } catch (IOException ex) {
                Logger.getLogger(frm_calculadora.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.txt_pantalla.setText("");
            }break;
        }
        
        
        
    }//GEN-LAST:event_mn_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mn_manual;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multip;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JFrame frm_lectura;
    private javax.swing.JFrame frm_manual;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adv;
    private javax.swing.JLabel lbl_op;
    private javax.swing.JMenuItem mn_historial;
    private javax.swing.JMenuItem mn_nuevo;
    private javax.swing.JTextArea txa_lectura;
    private javax.swing.JTextField txt_pantalla;
    // End of variables declaration//GEN-END:variables

    private BufferedWriter BufferedWriter(FileWriter fileWriter) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
